#!/bin/bash

for f in ./R/*~; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in ./inst/doc/*~; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./src/*.so; do
    rm -f $f
done

for f in ./src/*.o; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

#rm -rf inst/documentation/latex
#rm -rf inst/documentation/man

find . -name "DEADJOE" -exec rm -f {} \;

exit 0
